# Generated by Django 2.2.14 on 2020-07-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='arg1',
            field=models.CharField(default='sample', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='arg2',
            field=models.CharField(default='sample2', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
